//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skynetz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int Id { get; set; }
        public string Origem { get; set; }
        public string Destino { get; set; }
        public Nullable<int> Tempo { get; set; }
        public string Plano { get; set; }
        public Nullable<decimal> ComFaleMais { get; set; }
        public Nullable<decimal> SemFaleMais { get; set; }
    }
}
